const theme = {
    padding: {
        none: 0,
        xxxs: 5,
        sx: 10,
        xxs: 15,
        xs: 20,
        s: 80,
        buttonDefault: '5px 40px',
        buttonLaptop: '3px 15px',
        buttonTablet: '2px 0',
    },
    margin: {
        l: 10,
    },
    borderRadius: {
        none: 0,
        s: 5,
        l: 10,
        xl: 20,
    },
    border: {
        none: 0,
        s: 1,
    },
    fontSize: {
        xxxs: 3,
        xs: 15,
        s: 20,
        l: 25,
        xl: 30,
    },
    lineHeight: {
        l: 30,
        xl: 50,
    },
    width: {
        x5s: 12,
        x4s: 14,
        xxxs: 30,
        xs: 50,
        s: 60,
        m: 70,
        xxl: 80,
        xl: 90,
        x3l: 95,
        l: 100,
        lx: 140,
        x1l: 170,
        x2l: 200,
        xxxl: 250,
    },
    height: {
        x1s: 15,
        xxs: 20,
        xs: 25,
        sx: 30,
        x: 35,
        sssx: 40,
        s3x: 45,
        sl: 50,
        ssx: 60,
        s: 80,
        m: 90,
        ml: 95,
        l: 100,
        xl: 150,
    },
    colors: {
        black: '#000',
        white: '#fff',
        darkBlue: '#122e65',
        grey: 'grey,',
    },
    gap: {
        none: 0,
        l: 10,
        xl: 15,
        xxl: 35,
    },
    fontWeight: {
        l: 400,
        xl: 900,
    },
    zIndex: {
        l: 3,
    },
    top: {
        l: 45,
    },
    fontFamily: {
        default: 'Inter',
    },
    stroke: {
        s: 1,
        l: 1.5,
    },
};
export default theme;
